inherit_gem:
  sbmt-dev: config/rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 5.1

RSpec/VerifiedDoubles:
  Exclude:
    - spec/**/*_spec.rb

Rails/OverridingEnvVars:
  Exclude:
    - spec/spec_helper.rb
    - exe/kafka_consumer
