inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

require:
  - standard

inherit_gem:
  standard: config/base.yml

inherit_from:
  - rubocop/rspec.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0
  Exclude:
    - spec/internal/pkg/**/*

RSpec/VerifiedDoubles:
  Exclude:
    - spec/**/*_spec.rb

Style/SingleLineMethods:
  Enabled: false

Style/EmptyMethod:
  Enabled: false
