# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopper_registration.proto

require "google/protobuf/timestamp_pb"
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("shopper_registration.proto", syntax: :proto3) do
    add_message "sso.UserRegistration" do
      optional :user_uuid, :string, 1
      optional :phone, :string, 2
      optional :created_at, :message, 4, "google.protobuf.Timestamp"
    end
  end
end

module Sso
  UserRegistration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sso.UserRegistration").msgclass
end
